# Generated by Django 4.0.6 on 2022-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnoz',
            field=models.TextField(blank=True, default=''),
        ),
    ]
