# Generated by Django 4.0.6 on 2022-07-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientVisit',
        ),
    ]
