# Generated by Django 4.0.6 on 2022-08-06 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0006_alter_patient_address_alter_patient_date_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientbill',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientbill',
            name='service',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientbill',
            name='status',
            field=models.CharField(choices=[("To'langan", "To'langan"), ("To'lanmagan", "To'lanmagan")], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
