# Generated by Django 4.0.6 on 2022-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patientbill_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbill',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
