# Generated by Django 4.0.6 on 2022-08-06 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patientbill_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbill',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
