# Generated by Django 4.0.6 on 2022-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnoz',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='AppointmentListView',
        ),
    ]
