# Generated by Django 4.0.6 on 2022-07-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_appointment_diagnoz_delete_appointmentlistview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='diagnoz',
        ),
        migrations.AddField(
            model_name='appointment',
            name='qaydlar',
            field=models.TextField(default='', null=True),
        ),
    ]
