# Generated by Django 4.0.6 on 2022-08-05 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_address_alter_patient_date_recorded_and_more'),
        ('doctors', '0004_alter_appointment_qaydlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='sana'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='bemor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Yakunlandi', 'Yakunlandi'), ('Kutilmoqda', 'Kutilmoqda'), ('Bekor qilindi', 'Bekor qilindi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='vaqt'),
        ),
    ]
