# Generated by Django 4.0.6 on 2022-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_remove_invoice_due_date_alter_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='message',
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name="To'lov qaydlari"),
        ),
    ]
