# Generated by Django 4.0.6 on 2022-08-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_remove_invoice_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
    ]
