# Generated by Django 4.0.6 on 2022-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_lineitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.TextField(default='', verbose_name="To'lov qaydlari"),
        ),
    ]
