# Generated by Django 4.0.6 on 2022-08-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_lineitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='description',
        ),
    ]
