# Generated by Django 4.0.6 on 2022-08-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_rename_customer_invoice_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
